# ----------------------------------------------------------------------
# English

en:
  contentDir: content/en
  disabled: false
  locale: "en-US"
  label: English
  weight: 1
  
  params:
    description: I'm Xicu, an Electronic Engineer passionate about Electrons, Computers and Philosophy. Here you will find my blog, projects and more.
    profileMode:
      title: Welcome to my website! 👋
      subtitle: I'm **Xicu**, an Electronic Engineer passionate about Electrons, Computers and Philosophy. Here you will find my blog, projects and more. Enjoy your stay! 🚀
      buttons:
        - name: About me
          url: /en/cv
        - name: Blog
          url: /en/posts
        - name: Projects
          url: /en/projects

    socialIcons:
    - name: Email
      url: /en/contact
    - name: LinkedIn
      url: https://www.linkedin.com/in/xicu
    - name: Github
      url: https://github.com/XicuM
    - name: Instagram
      url: https://www.instagram.com/xicu.m

  menu:
    main:
      - identifier: cv
        name: About me
        url: /en/cv
        weight: 1
      - identifier: blog
        name: Blog
        url: /en/posts
        weight: 2
      - identifier: projects
        name: Projects
        url: /en/projects
        weight: 3
      - identifier: contact
        name: Contact
        url: /en/contact
        weight: 4

# ----------------------------------------------------------------------
# Español

es:
  contentDir: content/es
  disabled: false
  locale: "es-ES"
  label: Español
  weight: 2

  params:
    description: Soy Xicu, un Ingeniero Electrónico apasionado por los Electrones, los Ordenadores y la Filosofía. Aquí encontrarás mi blog, proyectos y más. ¡Disfruta tu visita!
    profileMode:
      title: ¡Bienvenido a mi sitio web! 👋
      subtitle: Soy **Xicu**, un Ingeniero Electrónico apasionado por los Electrones, los Ordenadores y la Filosofía. Aquí encontrarás mi blog, proyectos y más. ¡Disfruta tu visita! 🚀
      buttons:
      - name: Sobre mí
        url: /es/cv
      - name: Blog
        url: /es/posts
      - name: Proyectos
        url: /es/projects

    socialIcons:
    - name: Email
      url: /es/contact
    - name: LinkedIn
      url: https://www.linkedin.com/in/xicu
    - name: Github
      url: https://github.com/XicuM
    - name: Instagram
      url: https://www.instagram.com/xicu.m

  menu:
    main:
      - identifier: cv
        name: Sobre mí
        url: /es/cv
        weight: 10
      - identifier: blog
        name: Blog
        url: /es/posts
        weight: 20
      - identifier: projects
        name: Proyectos
        url: /es/projects
        weight: 30
      - identifier: contact
        name: Contacto
        url: /es/contact
        weight: 40